[package]
name = "Decision_Tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
csv = "1.1"
ndarray = "0.15.6"
linfa = "0.7.0"
linfa-trees = "0.7.0"
rand = "0.8.5"
